modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# 7. LICENSE
license="MIT"

[[mods]] #mandatory

# 8. MODID
modId="<modid>" #mandatory
version="${file.jarVersion}" #mandatory

# 9. MODNAME (USER FRIENDLY)
displayName="<modname>" #mandatory

# 10. URL (OPTIONAL)
displayURL="" #optional

# 11. USERNAME (OPTIONAL)
authors="<username>" #optional

# 12. DESCRIPTION (OPTIONAL)
description='''

'''

[[dependencies.examplemod]] #mandatory
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
